export const SET_CREATE_METADT_OVERLAY = "SET_CREATE_METADT_OVERLAY";
export const GET_ALL_META_DTs = "GET_ALL_META_DTs";
export const GET_META_DT = "GET_META_DT";
export const GET_META_DT_DETAIL = "GET_META_DT_DETAIL";